config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'tasks#index'
  delete 'logout', to: 'sessions#destroy'
  resources :tasks, :users, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # homepage (display all of the tasks)
  def index
    @tasks = Task.all
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
  end
# click on a link to go to a specific task page
  def show
    @task = Task.find(params[:id])
  end
# creating a new task, both methods (get @ post)
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end
# Updating a task (get & post)
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to root_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # This will create a new user when called
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'succsessfully created account'
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://api.fontshare.com/v2/css?f[]=archivo@700,100,600&f[]=clash-display@400,700,600,300&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <style>
    .task-link {
      text-decoration: none;
      color: black;
    }
    .task-link:hover {
      color: darkgrey;
      transition: .3s
    }
  </style>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">statusquo</a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container" style="text-align: center; max-width: 1100px; margin: 0px auto">
  <div class="title">
    <%= link_to root_path, class: "task-link" do%>
      <%# can add a link to home here if i want  %>
    <% end %>
    <h2>Edit Task</h2>
  </div>
  <div class="task-form">
    <%= form_with model: @task do |f| %>
    <%= f.check_box :completed %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="user-message">
  <% if @user %>
    <h2>Hello: <%= @user.email %></h2>
    <%= button_to 'Log out', logout_path, method: :delete, class: "main-page-button" %>
  <% end %>
</div>
<div class="container-home">
  <h2 style="font-weight: 400">TASKS</h2>
</div>
<div class="container-home">
  <div class="task-list">
    <ul style="list-style: none; font-size: 18px">
        <%# <h3 style="font-weight: 600">Tasks:</h3> %>
      <% @tasks.each do |task| %>
        <%= link_to task_path(task), class: "task-link" do %>
            <% if task.completed == true %>
              <li><label><input type="checkbox" name="html" value="html" checked><%= task.title %></label>
              <%= link_to "🗑", task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
            <% else %>
              <li><label><input type="checkbox" name="html" value="html"><%= task.title %></label>
              <%= link_to "🗑", task_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
            <% end %>
          <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <div class="add-task" style="text-align: start; margin-top: 40px; font-size: 20px">
    <%= link_to '+ Add a new task', new_task_path, class: "task-link" %>
  </div>
</div>

<div class="container">
  <%= link_to 'Sign Up', new_user_path, class: "bottom-page-button" %>
</div>

app/views/tasks/new.html.erb
<div class="container" style="text-align: center; max-width: 1100px; margin: 0px auto">
  <div class="title">
    <%= link_to root_path, class: "task-link" do%>
      <%# can add a link to home here if i want  %>
    <h2>Add a New Task</h2>
    <% end %>
  </div>
  <div class="task-form">
    <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container" style="text-align: center; max-width: 1100px; margin: 0px auto">
  <div class="title">
    <%= link_to root_path, class: "task-link" do%>
      <h2><%= @task.title %></h2>
    <% end %>
  </div>
  <div class="description" style="border: 1px solid black; border-radius: 5px; margin-bottom: 15px; background-color: lightgrey">
    <p style="font-size: 18px"><%= @task.details %></p>
  </div>
  <div class="completion-status">
    <% if @task.completed == true %>
      <label><input type="checkbox" name="html" value="html" checked> The task is completed!</label>
    <% else %>
      <label><input type="checkbox" name="html" value="html"> The task is NOT completed.</label>
    <% end %>
  </div>
  <div class="edit-task">
    <%= link_to edit_task_path, class: "task-link" do%>
      <h3>Edit Task</h3>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-user">
  <h1>Sign Up</h1>

  <div class="user-signup">
  <%= form_with model: @user, html: {class: "user-form"} do |f| %>
    <%= f.label :email, class: "input-label" %>
    <%= f.text_field :email, class: "input-box" %>
    <%= f.label :password, class: "input-label" %>
    <%= f.password_field :password, class: "input-box" %>
    <%= f.label :password_confirmation, class: "input-label" %>
    <%= f.password_field :password_confirmation, class: "input-box" %>
    <%= f.submit id: "submit-button" %>
  <% end %>
  </div>
</div>